# Generated by Django 3.2.8 on 2021-10-18 13:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_doctor', models.CharField(choices=[('hirurg', 'хирург'), ('terapevt', 'терапевт')], default='', max_length=10, verbose_name='Направление')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО врача')),
                ('passport_pin', models.IntegerField(null=True, verbose_name='ПИН-КОД паспорта')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('experience', models.CharField(max_length=10, verbose_name='Стаж работы')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200, unique=True, verbose_name='Название больницы')),
                ('region_of_hospital', models.CharField(choices=[('bishkek', 'Бишкек'), ('chuy', 'Чуй'), ('talas', 'Талас'), ('osh', 'Ош'), ('batken', 'Баткен'), ('naryn', 'Нарын'), ('djalal', 'Джалал-Абад'), ('issyk', 'Иссык-куль')], default='', max_length=25, verbose_name='Регион бальницы')),
                ('count_of_staff', models.IntegerField(default=1, help_text='Максимум 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Кол-во сотрудников')),
                ('type_of_hospital', models.BooleanField(default=True, help_text='Если больница государственная то 1, иначе 0', verbose_name='Тип больницы')),
            ],
        ),
        migrations.CreateModel(
            name='Nure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО медсестры')),
                ('passport_pin', models.IntegerField(null=True, verbose_name='ПИН-КОД паспорта')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('nurseForDoctors_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hospital_2.doctor', verbose_name='ФИО врача')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО медсестры')),
                ('passport_pin', models.IntegerField(null=True, verbose_name='ПИН-КОД паспорта')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('reason', models.CharField(max_length=100, verbose_name='Причина обращения в больницу')),
                ('doctorForPatient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_2.doctor', verbose_name='ФИО лечащего врача')),
                ('nure_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hospital_2.nure', verbose_name='ФИО пациента')),
            ],
        ),
        migrations.CreateModel(
            name='HeadOfDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО Главврача')),
                ('passport_pin', models.IntegerField(null=True, verbose_name='ПИН-КОД паспорта')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('experience', models.CharField(max_length=10, verbose_name='Стаж работы')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('hospitalForHead_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hospital_2.hospitals', verbose_name='Название больницы')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Привязка к user')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='headOfDoctors_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_2.headofdoctors', verbose_name='ФИО главрача'),
        ),
    ]
