<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-10-15 13:54
=======
# Generated by Django 3.2.8 on 2021-10-15 13:38
>>>>>>> 4a9444ef282364627b79fc5e00fabf5dd8e41f12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=200)),
                ('main_doctor', models.CharField(max_length=200)),
                ('hirurg', models.CharField(max_length=200)),
                ('terapevt', models.CharField(max_length=200)),
                ('medsestra', models.CharField(max_length=200)),
                ('pasienty', models.CharField(max_length=200)),
=======
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
>>>>>>> 4a9444ef282364627b79fc5e00fabf5dd8e41f12
            ],
        ),
    ]
