# Generated by Django 3.2.8 on 2021-10-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_2', '0002_auto_20211015_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='hirurg',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='terapevt',
            field=models.CharField(default='', max_length=200),
        ),
    ]
