# Generated by Django 3.2.8 on 2021-10-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_2', '0003_auto_20211015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='hirurg',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='terapevt',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
